services:
  db:
    image: postgres:17-alpine # Define stable postgres version
    container_name: adeona-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} # (optional, good for init.sql references)
    volumes:
      - pgdata:/var/lib/postgresql/data # Named volume for persistent Postgres data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Bind mount to run init SQL script at container start
    networks:
      - backend
    ports:
      - "5432:5432" # Expose Postgres default port for local access
    #Add Healthcheck to ensure DB is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Gives the DB time to init before health checks count failures
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # target: dev
      target: production
    container_name: adeona-backend
    env_file:
      - ./backend/.env
    # volumes:
    #   - ./backend:/app # Bind mount the backend source code to the container
    #   - backend_node_modules:/app/node_modules # Named volume to keep node_modules inside the container
    ports:
      - "3000:3000" # Expose backend app port
    networks:
      - backend
      - frontend
      # Wait for the db to finish setting up and ready to accept connection
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  frontend: #similar structure to backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # target: dev
      target: production
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3000
        - NEXT_PRIVATE_API_URL=http://backend:3000
    container_name: adeona-frontend
    environment:
      - WATCHPACK_POLLING=true
    # volumes:
    #   - ./frontend:/app
    #   - frontend_node_modules:/app/node_modules
    ports:
      # - "3001:3001" # dev port
      - "8080:8080" # production port
    networks:
      - frontend
    depends_on:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge # default but explicitly define bridge
  frontend:
    driver: bridge
volumes:
  pgdata: #let Docker handle the postgresdata
  backend_node_modules:
  frontend_node_modules:
